CC = gcc
CFLAGS = -Wall -Wextra
TARGETS = server client

all: $(TARGETS)

server: server.c
	$(CC) $(CFLAGS) -o server server.c

client: client.c
	$(CC) $(CFLAGS) -o client client.c

clean:
	rm -f $(TARGETS) p1_in p1_out p2_in p2_out

run: all
	./server